[package]
name = "ImageGridOptimizer"
version = "0.1.0"
authors = ["Ludger Radke"]
edition = "2021"

[dependencies]
image = "0.24.7"
clap = "2.33.0"
rayon = "1.5"
indicatif = "0.17.6"
rand = "0.8"
rect_packer = "0.2.1"
